# Generated by Django 6.1.1 on 2026-10-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
